from .formulario_carga import Formulario_main
from .GUI_OPCIONES import Formulario_opciones
from .GUI_menu_score import From_menu_score
from .GUI_niveles import Formulario_niveles
from .GUI_button import Button
from .GUI_slider import Slider
from .GUI_textbox import TextBox
from .GUI_label import Label
from .GUI_form import Form
from .GUI_button_image import Button_Image
from .MENU_PAUSA import FormularioPausa
from .menu_puntuacion import From_menu_puntuacion